In [1]:
import math 
math.sqrt(10)

3.1622776601683795

In [3]:
import math as m
m.sqrt(10)

3.1622776601683795

In [5]:
import numpy as np

Numpy array has similar data type

In [16]:
#how to create numpy arrays
l = [1,2,3,4]
a = np.array(l)
print(a)
print(a.dtype)

l = [1,2,"3"]
a = np.array(l)
print(a)
print(a.dtype)

b = np.zeros(10)    
print(b)
b[0] ="1"   #convert "1" into int 1.
print(b.dtype)

b = np.zeros(10,int)
print(b)
print(b.dtype)


#multi-dimensional arrays 
c = np.zeros((2,3,4))           #pass tuple as argument

[1 2 3 4]
int64
['1' '2' '3']
<U21
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
float64
[0 0 0 0 0 0 0 0 0 0]
int64


In [25]:
c[0][1][2]

#slicing
a[2:4]

c.shape      #give the size of n-dimensional matrix


a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a[0])      #all element in 0th row
print(a[:,0])       #all elemnts in 0th column
print(a[0:2, 0])   #all elements in 0-2sliced row and 0th column
print(a[:,2:4])



[1 2 3]
[ 1  4  7 10]
[1 4]
[[ 3]
 [ 6]
 [ 9]
 [12]]


so basically we can any subarray from a n-dimensional . array by syntax

a[startrow:endrow, startcol:endcol]

which slices matrix from index startrow to endrow-1 and startcol to endcol-1

In [26]:
  np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a = np.array([0, 1, 2, 3])
a.shape


(4,)

In [34]:
#NUMPY operations 

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+2)         # added element wise
print(a+b)         # add corrsponding elements in both the array if dimensions are same otherwise error

print(a*2)
print(a*b)

print(a ** 2)
print(a ** b)


[3 4 5]
[5 7 9]
[2 4 6]
[ 4 10 18]
[1 4 9]
[  1  32 729]


In [37]:

print(a.mean())
print(a.sum())

2.0
6


In [41]:
#distance between two points a and b in space whose coordinates are given 

a = np.array([1,2,3])
b = np.array([4,5,6])

d2 = ((a-b) ** 2).sum()
d = m.sqrt(d2)

print(d)



5.196152422706632


In [44]:
x = np.array([1,3,5,6])
((x-x.mean()) ** 2).sum()

14.75

In [45]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[10,20],[30,40]])

a1.dot(a2)        #dot product

array([[ 70, 100],
       [150, 220]])

np.mat()      #numpy matrix 
 
basically generalised 2d form of numpy arrays

speciality is when we write a*b then it does not multiply element wise rather it does by actual multiplication of 2d matrices 


In [47]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 3, 4, 5])
a.dot(b)

26

In [48]:
a = np.matrix('1 2 4; 3 4 5')
a.shape

(2, 3)

In [49]:
    np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])