In [1]:
import numpy as np

In [2]:
## AND function 
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

#### Sigmoid Function

$$ sig(z) = \frac{1}{1+e^{-z}} $$
where,  
$$ z = (x_1*w_1 + x_2 * w_2 + ... + x_n * w_n) $$

In [3]:
## Defining sigmoid function
def sigmoid(z):
    return 1/(1 + np.exp(-z))

#### Derivative of Sigmoid Function
$$ \frac{d(sig(z))}{dz} = sig(z) * [1 - sig(z)] $$

In [4]:
## Defining derivative of sigmoid function
def derivativeSigmoid(z):
    return sigmoid(z) * (1 - sigmoid(z))

## Forward Propagation without any hidden layer

In [5]:
## Initialising with random weights

weights = 2 * np.random.random((2,1)) - 1
bias = 2 * np.random.random(1) - 1
learning_rate = 0.1
## Multiplying with 2 moves the range from (0,1) to (0,2) 
## Subtracting 2 from it, moves the range from (0,2) to (-1,1)

weights, bias

(array([[-0.53464486],
        [ 0.13990193]]), array([ 0.42076711]))

In [6]:
output0 = X
output = sigmoid(np.dot(output0, weights) + bias )
output

array([[ 0.6036668 ],
       [ 0.63660733],
       [ 0.47156129],
       [ 0.50650568]])

## Neural Network Implementation without any hidden Layer

Derivative of Error with respect to weight between ith unit of a layer to jth unit of next layer.
$$ \frac{d(Error)}{dw_{ij}} = \frac{d(Error)}{dO_j} * \frac{dO_j}{d(input_j)} * \frac{d(input_j)}{dw_{ij}} $$

$$ \implies  \frac{d(Error)}{dw_{ij}} = (y_{pred} - y_{actual}) * O_j(1-O_j) * O_i $$

In [7]:
for iter in range(10000):
    output0 = X
    output = sigmoid(np.dot(output0, weights) + bias )
    
    first_term = output - Y

    input_j = np.dot(output0, weights) + bias
    second_term = derivativeSigmoid(input_j)

    first_two = first_term * second_term

    changes = np.dot(output0.T, first_two)
    weights = weights - learning_rate * changes

    bias_change = np.sum(first_two)    
    bias = bias - learning_rate * bias_change
    
output = sigmoid(np.dot(X, weights) + bias )
print("Weights : ",weights)
print("Bias : ", bias)
print("output : ", output)

Weights :  [[ 5.47246921]
 [ 5.47246922]]
Bias :  [-8.3014269]
output :  [[  2.48100901e-04]
 [  5.57792692e-02]
 [  5.57792687e-02]
 [  9.33609949e-01]]


## Forward Propagation with 1 hidden layers

In [8]:
# Hidden layer weights
wh = 2 * np.random.random((2,2)) - 1

# Hidden layer biases
bh = 2 * np.random.random((1,2)) - 1

# Output Weights
wo = 2 * np.random.random((2,1)) - 1

# Output Biases
bo = 2 * np.random.random((1,1)) - 1

In [9]:
output0 = X
outputHidden = sigmoid(np.dot(output0, wh) + bh)
output = sigmoid(np.dot(outputHidden, wo) + bo)
output

array([[ 0.39265954],
       [ 0.41346297],
       [ 0.39258015],
       [ 0.41685322]])