In [1]:
import numpy as np

In [12]:
## AND function 
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

#### Sigmoid Function

$$ sig(z) = \frac{1}{1+e^{-z}} $$
where,  
$$ z = (x_1*w_1 + x_2 * w_2 + ... + x_n * w_n) $$

In [3]:
## Defining sigmoid function
def sigmoid(z):
    return 1/(1 + np.exp(-z))

#### Derivative of Sigmoid Function
$$ \frac{d(sig(z))}{dz} = sig(z) * [1 - sig(z)] $$

In [15]:
## Defining derivative of sigmoid function
def derivativeSigmoid(z):
    return sigmoid(z) * (1 - sigmoid(z))

## Forward Propagation without any hidden layer

In [8]:
## Initialising with random weights

weights = 2 * np.random.random((2,1)) - 1
bias = 2 * np.random.random(1) - 1

## Multiplying with 2 moves the range from (0,1) to (0,2) 
## Subtracting 2 from it, moves the range from (0,2) to (-1,1)

weights, bias

(array([[-0.66828348],
        [-0.80674224]]), array([ 0.82902779]))

In [11]:
output0 = X
output = sigmoid(np.dot(output0, weights) + bias )
output

array([[ 0.69614932],
       [ 0.50557116],
       [ 0.54009977],
       [ 0.34389196]])

## Forward Propagation with 1 hidden layers

In [13]:
# Hidden layer weights
wh = 2 * np.random.random((2,2)) - 1

# Hidden layer biases
bh = 2 * np.random.random((1,2)) - 1

# Output Weights
wo = 2 * np.random.random((2,1)) - 1

# Output Biases
bo = 2 * np.random.random((1,1)) - 1

In [14]:
output0 = X
outputHidden = sigmoid(np.dot(output0, wh) + bh)
output = sigmoid(np.dot(outputHidden, wo) + bo)
output

array([[ 0.43878984],
       [ 0.45954717],
       [ 0.43606245],
       [ 0.45160246]])